project:
  type: book
    
book:
  title: "Multiple imputation-propensity score workflows"
  subtitle: "Examples for multiple imputation and propensity score workflows"
  author: "Janick Weberpals"
  description: |
    Miscellaneous multiple imputation and propensity score workflows
    
  chapters:
    # landing page
    - index.qmd
    - chapters/whole_game.qmd
    - chapters/syvcox_coxph.qmd
    - chapters/re_weight.qmd
    - chapters/subgroup_analysis.qmd

  reader-mode: true
  repo-url: https://github.com/janickweberpals/imputation-ps-workflows
  repo-actions: [issue]

format:
  html:
    theme: journal
    code-fold: true
    code-summary: "Show the code"
    engine: knitr
    page-layout: full
    link-external-icon: true
    link-external-newwindow: true

