#!/bin/sh

R -e "install.packages('pak')"

R -e "pak::pak('tidyverse@1.1.6')"
R -e "pak::pak('survival@3.5-8')"
R -e "pak::pak('mice@3.18.0')"
R -e "pak::pak('MatchThem@1.2.1')"
R -e "pak::pak('survey@4.4-2')"
R -e "pak::pak('here@1.0.1')"
R -e "pak::pak('gtsummary@2.3.0')"
R -e "pak::pak('parallelly@1.45.0')"
R -e "pak::pak('ranger@0.17.0')"
R -e "pak::pak('furrr@0.3.1')"
R -e "pak::pak('cobalt@4.6.0')"
R -e "pak::pak('gsDesign@3.6.9')"
R -e "pak::pak('yaml@2.3.10')"
R -e "pak::pak('gt@1.0.0')"
R -e "pak::pak('marginaleffects@0.28.0')"
R -e "pak::pak('tictoc@1.2.1')"
R -e "pak::pak('tibble@3.3.0')"
R -e "pak::pak('rmarkdown@2.29')"
R -e "pak::pak('pander@0.6.6')"
R -e "pak::pak('sessioninfo@1.2.3')"

R -e "pak::pak('janickweberpals/encore.analytics@dev')"
